# code: language=ansible
---
# tasks file for code

- name: Install requirements
  become: true
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - wget
      - gpg
    state: present

- name: Dowload gpg key and configure VsCode repo
  become: true
  block:
  - name: Add gpg signing key from Microsoft
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
      mode: '0440'

  - name: Add VsCode repo to source.list
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main"
      state: present

- name: Install VsCode
  become: yes
  ansible.builtin.apt:
    name: code
    state: present

# - name: 'Ensure directory exists: {{ code_setting_path }}'
#   ansible.builtin.file:
#     path: '{{ code_setting_path }}'
#     state: directory
#     mode: "0755"


# - name: Setup VsCode settings and keybindings
#   ansible.builtin.file:
#     src: '{{ role_path }}/files/{{ item }}'
#     dest: '{{ code_setting_path }}/{{ item }}'
#     state: link
#     force: true
#   loop:
#     - keybindings.json'
#     - settings.json

- name: Install VsCode extensions
  ansible.builtin.command: code --install-extension '{{ item }}'
  with_items: '{{ vscode_plugins }}'
  when: vscode_plugins | length > 0
  register: vscode_extensions_check
  changed_when: "'already installed' not in vscode_extensions_check.stdout"

# - name: Setup sysctl to fix warning to large workspace in vscode
#   become: true
#   ansible.posix.sysctl:
#     name: fs.inotify.max_user_watches
#     value: '524288'
#     state: present
#     reload: true
