# code: language=ansible
---
# tasks file for code

- name: Run "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
  changed_when: no

- name: Install requirements
  become: true
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - wget
      - gpg
    state: present


- name: Dowload gpg key and configure VsCode repo
  block:
    - name: Add gpg signing key from Microsoft
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/trusted.gpg.d/microsoft.asc

    - name: Add VsCode repo to source.list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main"
        state: present

- name: Install VsCode
  become: yes
  ansible.builtin.apt:
    name: code
    state: present

# - name: Install vscode package
#   become: true
#   ansible.builtin.apt:
#     deb: '{{ item.value }}'
#   loop: '{{ deb_packages | dict2items }}'

      #- name: Install snapd package
      #ansible.builtin.package:
      #name: snapd
      #state: present
      #become: true

    #- name: Install VsCode snap package
    #become: true
    #snap:
    #name: code
    #classic: true

# - name: 'Ensure directory exists: {{ bashrc_folder }}'
#   ansible.builtin.file:
#     path: '{{ bashrc_folder }}'
#     state: directory
#     mode: "0755"

# - name: 'Ensure directory exists: {{ code_setting_path }}'
#   ansible.builtin.file:
#     path: '{{ code_setting_path }}'
#     state: directory
#     mode: "0755"

# - name: Create symbolic link to code aliases in '{{ bashrc_folder }}'
#   ansible.builtin.file:
#     src: '{{ role_path }}/files/aliases.bash'
#     dest: '{{ bashrc_folder }}/code.bash'
#     state: link
#     force: true

# - name: Setup VsCode settings and keybindings
#   ansible.builtin.file:
#     src: '{{ role_path }}/files/{{ item }}'
#     dest: '{{ code_setting_path }}/{{ item }}'
#     state: link
#     force: true
#   loop:
#     - keybindings.json
#     - settings.json

# - name: Import VsCode extensions
#   ansible.builtin.command: code --install-extension {{ item }}
#   with_items: '{{ code_plugins }}'
#   changed_when: true

# - name: Setup sysctl to fix warning to large workspace in vscode
#   become: true
#   ansible.posix.sysctl:
#     name: fs.inotify.max_user_watches
#     value: '524288'
#     state: present
#     reload: true
