---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
