---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: Ubuntu-Focal
    image: ubuntu:20.04
    # privileged: true
    # pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
